name = "reader"
main = "workers.ts"
compatibility_date = "2024-01-01"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "reader"
database_id = "ef86a305-24a7-4aaa-97d9-b72064f79a27"
