name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: reader_test
          POSTGRES_USER: reader_user
          POSTGRES_PASSWORD: reader_pass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - uses: actions/checkout@v3

      - name: install raadability
        run: npm i

      - name: Test
        run: make test
        env:
          RD_DB_USER: reader_user
          RD_DB_NAME: reader_test
          RD_DB_PASSWD: reader_pass
          RD_DB_HOST: localhost
